title: Tongium's Blog
description: A blog about random things that I find interesting.
timezone: Asia/Bangkok
author:
  name: Tongium
google_analytics: # Add your ID here if you have one
show_excerpts: true # Helps with AEO and main page flow
